#!/bin/bash

#do run this with openfoam v8
#create mesh
blockMesh

#Copy the 0.orig to 0
cp -r 0.orig 0

#map U from openfoam v2012
mapFields ../caseof2106/



echo "-----------------------"
echo "Visualize in paraview"
echo "-----------------------"